### ISSUE TITLE
Can not build app

### ISSUE THREAD

**Issue by shalva97** [phicdy/MyCuration#301]
Hello, was interested by this app and tried to build it. Gradle throws lots of errors, similar to this ( about 80 of them)
```
75: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJniLibFolders'.
> org/w3c/dom/ElementTraversal
```

how can I fix that?

**Comment by phicdy** [comment]
Hi @shalva97,

Sorry for your inconvenience. I updated the environment by https://github.com/phicdy/MyCuration/pull/303.

I succeeded to build the project and passed CI.
Could you please check it ?
